# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "720bd9ac5905a1a3e59b65436919d40f"
name = "RemixStoreApp"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_orders,read_customers"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]
