# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "720bd9ac5905a1a3e59b65436919d40f"
name = "RemixStoreApp"
application_url = "https://shopify-remix-project.vercel.app"
embedded = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,write_products"

[auth]
redirect_urls = [
  "https://remix-store-app-v2.vercel.app/api/auth",
  "https://remix-store-app-v2.vercel.app/api/auth/callback",
  "https://remix-store-app-v2.vercel.app/auth/callback",  # これを追加
  "https://remix-store-app-v2.vercel.app/auth/shopify/callback"
]
